version: '3.1'
services:
  postgres:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=order_management
      - POSTGRES_USER=order_management
      - POSTGRES_PASSWORD=order_management
